USE master;

ALTER DATABASE SirketDB
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;


RESTORE DATABASE SirketDB
FROM DISK = 'C:\Backup\SirketDB_full.bak'
WITH NORECOVERY;

RESTORE LOG SirketDB
FROM DISK = 'C:\Backup\SirketDB_log1.trn'
WITH NORECOVERY;

RESTORE LOG SirketDB
FROM DISK = 'C:\Backup\SirketDB_log2.trn'
WITH NORECOVERY;

RESTORE LOG SirketDB
FROM DISK = 'C:\Backup\SirketDB_log3.trn'
WITH RECOVERY;